# Generated by Django 4.1.7 on 2023-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('C_password', models.CharField(max_length=40)),
            ],
        ),
    ]
