# Generated by Django 4.1.6 on 2023-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FMT',
            field=models.BooleanField(default=True),
        ),
    ]
