# Generated by Django 4.1.6 on 2023-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jarkhand', 'Jarkhand'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Uttarpradesh', 'Uttarpradesh'), ('HimachalPradesh', 'HimachalPradesh'), ('Goa', 'Goa'), ('Bingaluru', 'Bingaluru'), ('Rajasthan', 'Rajasthan')], max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pimage', models.ImageField(blank=True, upload_to='pimage')),
                ('rdoc', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
