# Generated by Django 4.0.3 on 2022-09-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_addressdetails_employee_remove_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressdetails',
            old_name='employee',
            new_name='addressDetails',
        ),
    ]
